- hosts: node 
  become: true
  tasks:
    - name: Create new webapp deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml 
    - name: Create new webapp service
      command: kubectl apply -f /home/ubuntu/service.yaml
