- hosts: node
  become: true
  tasks:
    - name: Create new webapp deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml --validate=false
    - name: Create new webapp service
      command: kubectl apply -f /home/ubuntu/service.yaml --validate=false
