apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
